version: '3.8'

services:
  node-app:
    # container_name: node-container-prod
    build: 
      context: ./
    # ports:
      # - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017/
    deploy:
      replicas: 3

  react-app:
    build: 
      context: ./react-app
    ports:
      - "5173:5173"
    volumes:
      - ./react-app/src:/src
  
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # ports:
      # - "27019:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6370:6379"

  nginx:
    image: nginx
    ports:
     - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      # - ./nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - node-app
      - react-app

volumes:
  mongo-data:
